# Generated by Django 4.2.1 on 2023-06-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_address_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
